safe: false

# build settings
markdown: kramdown
highlighter: pygments
lsi: false
permalink: /:title
paginate:     8
timezone: TIMEZONE

title: wztao'blog
description: hi ! This is wztao
baseurl: /blog
url: /blog # replace by your site's url
twitter_username: wztao
github_username:  wztao # (your name)
accent: "#f7f7e6" # accent color for blog column

author: wztao
address: ""
email: ""
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# clude files
include: [".htaccess"]
exclude:
  - LICENSE
  - README.md
